owner: Zenith-Sosuke
repo: status
sites:
  - name: Website
    url: https://celestia.rest
  - name: API
    url: https://sorayomi-api.onrender.com
assignees:
  - Zenith-Sosuke
status-website:
  cname: status.celestia.rest
  name: Celestia Status
