owner: Zenith-Sosuke
repo: status
sites:
  - name: Website
    url: https://celestia.rest
  - name: Bot
    url: http://fi11.bot-hosting.net:20267/api/health
  - name: API
    url: https://sorayomi-api-rr4k.onrender.com
assignees:
  - Zenith-Sosuke
status-website:
  cname: status.celestia.rest
  name: Celestia Status
  faviconUrl: https://celestia.rest/favicon.png
  logoUrl: https://celestia.rest/favicon.png
